/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    Dock: typeof import('./src/components/Dock.vue')['default']
    DocView: typeof import('./src/components/DocView.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MyTodos: typeof import('./src/components/MyTodos.vue')['default']
    OSDropdown: typeof import('./src/components/OSDropdown.vue')['default']
    OSWindow: typeof import('./src/components/OSWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    StatusPill: typeof import('./src/components/StatusPill.vue')['default']
    WallpaperPicker: typeof import('./src/components/WallpaperPicker.vue')['default']
  }
}

// For TSX support
declare global {
  const CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
  const Dock: typeof import('./src/components/Dock.vue')['default']
  const DocView: typeof import('./src/components/DocView.vue')['default']
  const MenuBar: typeof import('./src/components/MenuBar.vue')['default']
  const MyTodos: typeof import('./src/components/MyTodos.vue')['default']
  const OSDropdown: typeof import('./src/components/OSDropdown.vue')['default']
  const OSWindow: typeof import('./src/components/OSWindow.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
  const StatusPill: typeof import('./src/components/StatusPill.vue')['default']
  const WallpaperPicker: typeof import('./src/components/WallpaperPicker.vue')['default']
}