/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDashboard: typeof import('./src/components/Window/AppDashboard.vue')['default']
    AppSidebar: typeof import('./src/components/Window/AppSidebar.vue')['default']
    AppToolbar: typeof import('./src/components/Window/AppToolbar.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette/CommandPalette.vue')['default']
    Dock: typeof import('./src/components/Dock/Dock.vue')['default']
    DoctypeView: typeof import('./src/components/Views/DoctypeView.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/MenuBar.vue')['default']
    OSContextMenu: typeof import('./src/components/OSContextMenu.vue')['default']
    OSDropdown: typeof import('./src/components/OSDropdown.vue')['default']
    OSForm: typeof import('./src/components/Form/OSForm.vue')['default']
    OSList: typeof import('./src/components/List/OSList.vue')['default']
    OSListView: typeof import('./src/components/List/OSListView.vue')['default']
    OSWindow: typeof import('./src/components/Window/OSWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/Settings/SettingsDialog.vue')['default']
    StatusPill: typeof import('./src/components/StatusPill.vue')['default']
    WallpaperPicker: typeof import('./src/components/Settings/WallpaperPicker.vue')['default']
    WindowChrome: typeof import('./src/components/Window/WindowChrome.vue')['default']
  }
}

// For TSX support
declare global {
  const AppDashboard: typeof import('./src/components/Window/AppDashboard.vue')['default']
  const AppSidebar: typeof import('./src/components/Window/AppSidebar.vue')['default']
  const AppToolbar: typeof import('./src/components/Window/AppToolbar.vue')['default']
  const CommandPalette: typeof import('./src/components/CommandPalette/CommandPalette.vue')['default']
  const Dock: typeof import('./src/components/Dock/Dock.vue')['default']
  const DoctypeView: typeof import('./src/components/Views/DoctypeView.vue')['default']
  const MenuBar: typeof import('./src/components/MenuBar/MenuBar.vue')['default']
  const OSContextMenu: typeof import('./src/components/OSContextMenu.vue')['default']
  const OSDropdown: typeof import('./src/components/OSDropdown.vue')['default']
  const OSForm: typeof import('./src/components/Form/OSForm.vue')['default']
  const OSList: typeof import('./src/components/List/OSList.vue')['default']
  const OSListView: typeof import('./src/components/List/OSListView.vue')['default']
  const OSWindow: typeof import('./src/components/Window/OSWindow.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SettingsDialog: typeof import('./src/components/Settings/SettingsDialog.vue')['default']
  const StatusPill: typeof import('./src/components/StatusPill.vue')['default']
  const WallpaperPicker: typeof import('./src/components/Settings/WallpaperPicker.vue')['default']
  const WindowChrome: typeof import('./src/components/Window/WindowChrome.vue')['default']
}